project_id = "vbutzblgbexuwedzayjv"

[functions.fitbit-oauth-callback]
verify_jwt = false

[functions.fitbit-auth-url]
verify_jwt = true

[functions.fitbit-sync-sleep]
verify_jwt = true

[functions.oura-auth-url]
verify_jwt = true

[functions.oura-oauth-callback]
verify_jwt = false

[functions.oura-sync-sleep]
verify_jwt = true

[functions.validate-beta-token]
verify_jwt = false

[functions.send-beta-magic-link]
verify_jwt = false
